export const GET_PLANS_NBN_REQUEST = 'GET_PLANS_NBN_REQUEST';
export const GET_PLANS_NBN_SUCCESS = 'GET_PLANS_NBN_SUCCESS';
export const GET_PLANS_NBN_FAILURE = 'GET_PLANS_NBN_FAILURE';

export const GET_PLANS_5G_REQUEST = 'GET_PLANS_5G_REQUEST';
export const GET_PLANS_5G_SUCCESS = 'GET_PLANS_5G_SUCCESS';
export const GET_PLANS_5G_FAILURE = 'GET_PLANS_5G_FAILURE';

export const GET_PLANS_HOMEPHONE_REQUEST = 'GET_PLANS_HOMEPHONE_REQUEST';
export const GET_PLANS_HOMEPHONE_SUCCESS = 'GET_PLANS_HOMEPHONE_SUCCESS';
export const GET_PLANS_HOMEPHONE_FAILURE = 'GET_PLANS_HOMEPHONE_FAILURE';